var alltables = [
    {
        tableId:'t1',
        isOccupied:false,
        numberofChairs:4,
        orderedItems:[]
    },
    {
        tableId:'t2',
        isOccupied:true,
        numberofChairs:6,
        orderedItems:[]
    },
    {
        tableId:'t3',
        isOccupied:false,
        numberofChairs:2,
        orderedItems:[]
    },
    {
        tableId:'t4',
        isOccupied:false,
        numberofChairs:8,
        orderedItems:[]
    }
]